<?php

namespace Database\Seeders;

use App\Models\product\WavestoreProduct;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WavestoreProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // guitars
            [
                'item_ID'      => 'LPC79AJSB',
                'id_brand'     => 12,
                'id_category'  => 1,
                'model'        => 'Epiphone Adam Jones 1979 Les Paul Custom Electric Guitar - Antique Silverburst',
                'in_stock'     => true,
                'description'  => 'Solidbody Electric Guitar, Signature, with Maple Top, Mahogany Body, Maple Neck, Ebony Fingerboard, and 2 Humbucking Pickups - Antique Silverburst',
                'product_info' => 'Longtime listeners and eagle-eyed admirers of Tool’s Adam Jones have been waiting for an Epiphone iteration of his iconic axe, and that day has finally arrived. The Epiphone Adam Jones 1979 Les Paul Custom sports a feature set unique to late ’70s Gibson instruments; the body is a classic maple-on-mahogany construction, but the neck’s 3-piece maple design offers enhanced stability — it’s even further upgraded with a sleek piece of ebony for the fingerboard! Under the hood, a bridge-position Seymour Duncan Distortion delivers the same searing high-gain tones found on many a Tool album, while the inverted Gibson Custombucker offers a smooth PAF-style shimmer for your cleaner moments. Lastly, the Epiphone Adam Jones 1979 Les Paul Custom sports all the elegance of a late ’70s Les Paul Custom with multi-ply binding on just about every surface and a moody Silverburst finish.',
                'price'        => 1499.00,
                'img'          => '/img/items/guitars/epiphone/LPC79AJSB.png',
            ],
            [
                'item_ID'      => 'Strat70AV254SB',
                'id_brand'     => 1,
                'id_category'  => 1,
                'model'        => 'Fender Player II Stratocaster Electric Guitar - 3-color Sunburst with Rosewood Fingerboard',
                'in_stock'     => true,
                'description'  => 'Solidbody Electric Guitar with Alder Body, Maple Neck, Rosewood Fingerboard, and 3 Single-coil Pickups - 3-color Sunburst',
                'product_info' => 'Blending historic Fender panache with the necessary tools for modern performance, the Fender Player II Stratocaster delivers a suite of versatile tone-crafting capabilities. A trio of premium tonewoods comprises alder, maple, and rosewood, while Player series single-coil pickups span a spectrum of shimmering highs, tight lows, and sonorous midrange. Guitarists at Sweetwater are thrilled with Fender’s decision to introduce rolled edges to each axe’s fingerboards, augmenting both comfort and accessibility. What’s more, Fender dove deep into the archives to resurrect iconic finishes — some of which have never been seen in the series! Between eye-catching aesthetics and a 2-point synchronized tremolo, the Fender Player II Stratocaster is your key to unparalleled expression and next-level playability.',
                'price'        => 849.99,
                'img'          => '/img/items/guitars/fender/Strat70AV254SB.png',
            ],
            [
                'item_ID'      => 'LPSt60FTBbB',
                'id_brand'     => 13,
                'id_category'  => 1,
                'model'        => "Gibson Les Paul Standard '60s Figured Top Electric Guitar - Blueberry Burst",
                'in_stock'     => false,
                'description'  => 'Solidbody Electric Guitar with Mahogany Body, Maple Top, Mahogany Neck, Rosewood Fingerboard, and 2 Humbucking Pickups - Blueberry Burst',
                'product_info' => "The Gibson Les Paul Standard '60s Figured Top boasts the classic design that's kept this solidbody electric guitar relevant, played, and loved throughout the decades. You won't be able to take your eyes off this Les Paul Standard's figured maple top, and its '60s Burstbucker pickups milk every ounce of tone out of its musically resonant mahogany body. The Les Paul Standard '60s Figured Top's set mahogany neck wields Gibson's time-tested SlimTaper profile, and its Plek'd 12-inch-radius Indian rosewood fingerboard offers playability that's second to none. A Graph Tech nut, ABR-1 Tune-o-matic bridge, aluminum stopbar tailpiece, and Grover Rotomatic tuners with kidney buttons round out this Les Paul Standard's hardware. You also get single-ply body and fingerboard binding, acrylic trapezoid fingerboard inlays, a mother-of-pearl headstock logo, and a spotlight-stealing nitrocellulose lacquer finish. If you've been wanting a modern Les Paul with a slinky '60s feel and premium appointments, Sweetwater has your axe. The Gibson Les Paul Standard '60s Figured Top is the one you've been waiting for.",
                'price'        => 2799.00,
                'img'          => '/img/items/guitars/gibson/LPSt60FTBbB.png',
            ],
            [
                'item_ID'      => 'RG5320CDFM',
                'id_brand'     => 3,
                'id_category'  => 1,
                'model'        => "Ibanez Prestige RG5320C Electric Guitar - Deep Forest Green Metallic",
                'in_stock'     => false,
                'description'  => 'Solidbody Electric Guitar with Mahogany Body, 5-piece Maple/Wenge Neck, Macassar Ebony Fretboard, 2 Humbucking Pickups, and Tremolo - Deep Forest Green Metallic',
                'product_info' => "When you combine Ibanez's decades of guitar building expertise with player-centric upgrades and modifications, the result is the Ibanez Prestige RG5320C. Made with a lightweight mahogany body and 5-piece maple/wenge neck, this guitar flaunts a resonant tone that won't weigh you down over long gigs or sessions. It's loaded with a powerful pair of DiMarzio humbucking pickups — an Air Norton at the neck position and a Tone Zone at the bridge — with built-in coil tap capabilities to cover maximum tonal territory. And to make the ultra-thin Super Wizard HP neck even more playable, Ibanez rounded the fret edges with their Prestige fret edge treatment for an amazingly smooth feel. With its incredible playability and powerful tone, it's clear that the Ibanez Prestige RG5320C is made for the discerning player who needs to rock at high speed.",
                'price'        => 1299.00,
                'img'          => '/img/items/guitars/ibanez/RG5320CDFM.png',
            ],
            [
                'item_ID'      => 'JS32KEAVB',
                'id_brand'     => 14,
                'id_category'  => 1,
                'model'        => "Jackson Kelly JS32T - Viola Burst",
                'in_stock'     => true,
                'description'  => 'Solidbody Electric Guitar with Poplar Body, Maple Neck, Amaranth Fingerboard, and 2 Humbucking Pickups - Viola Burst',
                'product_info' => "Part of Jackson's JS Series, the JS32T Kelly solidbody electric guitar packs a lot of value. A pair of high-output ceramic-magnet humbuckers hits your amplifier with huge tone — just what you need for aggressive performance. And while the price is low, you'll be astounded at how good the JS32T Kelly plays. The compound-radius fretboard makes it easy to blaze around the neck, and the graphite-reinforced maple neck is designed for a long life of reliable action. Whether you're just starting to rock or are looking for a value-packed shred machine, you'll be impressed with the Jackson JS32T Kelly.",
                'price'        => 469.99,
                'img'          => '/img/items/guitars/jackson/JS32KEAVB.webp',
            ],
            [
                'item_ID'      => 'PAC012DLXVSB',
                'id_brand'     => 6,
                'id_category'  => 1,
                'model'        => "Yamaha PAC012DLX Pacifica Electric Guitar - Old Violin Sunburst",
                'in_stock'     => true,
                'description'  => "6-string Solidbody Electric with Mahogany Body, Maple Neck, Rosewood Fingerboard, and 2 Single-coil and 1 Humbucking Pickup - Old Violin Sunburst",
                'product_info' => "The Yamaha PAC012 Pacifica comes with a custom Yamaha ceramic humbucker in the bridge position, perfect for when you want to rock hard and heavy. Two single-coil pickups in the middle and neck positions offer up all kinds of clean, rocking single-coil tones as well. The range this trio of versatile pickups offers lets you explore all kinds of stylistic approaches in just about any genre — and at Sweetwater, we're all about exploration!",
                'price'        => 229.99,
                'img'          => '/img/items/guitars/yamaha/PAC012DLXVSB.png',
            ],
            // bass
            [
                'item_ID'      => 'JBassVP2MAOP',
                'id_brand'     => 1,
                'id_category'  => 2,
                'model'        => "Fender Player II Modified Active Jazz Bass V - Olympic Pearl, Maple Fingerboard",
                'in_stock'     => true,
                'description'  => "5-string Electric Bass Guitar with Alder Body, Maple Neck, Maple Fingerboard, and 2 Single-coil Pickups - Olympic Pearl",
                'product_info' => "Equally current and timeless, the Player II Modified Jazz Bass V beautifully blends the J Bass's storied heritage with modern flair in the form of quality tonewoods, high-performance hardware, and reimagined electronics. Featuring a classic construction, the Player II Modified Jazz Bass V offers contemporary comforts Sweetwater's Fender loyalists cannot do without, such as the modern C-shaped maple neck with smooth rolled edges that pairs with the maple fingerboard to deliver clear, articulate tone. To enhance and amplify that tone, Fender has introduced an all-new preamp with a refined 3-band EQ optimized for sonic transparency and an Active/Passive functionality that offers players ultimate flexibility when shaping their sound. Likewise, the Player II Modified J Bass V sports a set of newly voiced Noiseless pickups that serve as the bedrock for versatile Jazz Bass growl. Alongside these upgrades, Fender added some touches it knew the discerning player would appreciate — namely, a 1.875-inch TUSQ nut, tapered shaft tuners, and a HiMass bridge for enhanced intonation, sustain, and stability. For over half a century, the J Bass has masterfully held down the low end on countless records and performances — the captivating Player II Modified Jazz Bass V assuredly carries that legacy forward.",
                'price'        => 1209.99,
                'img'          => '/img/items/bass/fender/JBassVP2MAOP.webp',
            ],
            [
                'item_ID'      => 'RMBlondieSt',
                'id_brand'     => 2,
                'id_category'  => 2,
                'model'        => "Fodera Ryan Martinie 'Blondie' Standard 5-string Bass Guitar - Natural Maple",
                'in_stock'     => true,
                'description'  => "5-string Electric Bass, Signature, with Korina Body, Maple Top, Maple Neck, Ebony Fingerboard, and 2 Single-coil Pickups - Natural Maple",
                'product_info' => "One of metal’s most beloved bassists, Ryan Martinie has inspired generations of new players with his inventive techniques and imaginative style. Most known for his work with Mudvayne, Martinie has also worked with Soften The Glare and Korn. Now, Fodera and Martinie have joined forces to produce a bass worthy of its namesake: the Fodera 5-string Ryan Martinie 'Blondie' Standard. This bass features a shortened Monarch body style made from korina with curly maple, with an eye-grabbing zig-zag top. You’ll also have access to dual slant-mounted EMG J/J5 pickups that pump out tones ripe for metal, jazz, and everything in between. Ready to plug in? The Fodera 5-string Ryan Martinie 'Blondie' Standard is waiting for you here at Sweetwater.",
                'price'        => 6800.00,
                'img'          => '/img/items/bass/fodera/RMBlondieSt.webp',
            ],
            [
                'item_ID'      => 'SR375EFBBT',
                'id_brand'     => 3,
                'id_category'  => 2,
                'model'        => "Ibanez Standard SR375E Fretless 5-string Bass Guitar - Brown Burst",
                'in_stock'     => true,
                'description'  => "5-string Fretless Electric Bass with Maple Body, Maple/Rosewood Neck, Jatoba Fretboard, and 2 Humbucking Pickups",
                'product_info' => "Pick up the Ibanez SR375E fretless electric bass, and you'll quickly discover that Ibanez didn't sacrifice quality to bring you a such a value-packed bass guitar. In fact, the experience of playing the SR305E is much like that of Ibanez's higher-end SR Series models, thanks to the SR375E's sleek 5-piece maple/rosewood neck and comfortable maple arched body. A pair of Ibanez PowerSpan humbucking pickups pack a phenomenal punch, while a 3-band EQ with Power Tap creates a vast array of sound-shaping possibilities. When budding bass players are looking for a quality instrument, many Sweetwater Sales Engineers place the Ibanez SR375E electric bass at the top of their list.",
                'price'        => 529.99,
                'img'          => '/img/items/bass/ibanez/SR375EFBBT.webp',
            ],
            [
                'item_ID'      => 'MEHPJ5MpFBSS',
                'id_brand'     => 4,
                'id_category'  => 2,
                'model'        => "Sadowsky MetroExpress Hybrid P/J 5-string Bass Guitar - Solid Silver Metallic",
                'in_stock'     => false,
                'description'  => "5-string Electric Bass with Okoume Body, Roasted Maple Neck, Roasted Maple Fingerboard, and 2 Single-coil Pickups - Solid Silver Metallic",
                'product_info' => "Sadowsky’s MetroExpress 21-fret Hybrid P/J Bass seamlessly blends classic aesthetics with contemporary functionality and exceptional playability. Crafted with an okoume body, renowned for its lightweight and resonant qualities, this bass provides a rich tonal foundation. The roasted maple neck fortifies stability and strength while offering a smooth, comfortable playing experience, while the 21-fret roasted maple fingerboard adds a touch of snap and presence to the overall sound profile. Each MetroExpress Bass is equipped with Sadowsky’s signature enhancements, including advanced 2-band active electronics that allow for precise tonal adjustments, catering to a wide range of musical styles. The adjustable Just-A-Nut ensures optimal string height and intonation, improving playability. Additionally, the quick string release bridge facilitates effortless string changes, making maintenance a breeze. The noiseless P-and-J-style pickups deliver a clean, dynamic sound with excellent clarity, further enhancing tonal versatility. It all equates to a Sadowsky bass that is not only visually striking, but also a powerhouse of performance.",
                'price'        => 1160.00,
                'img'          => '/img/items/bass/sadowsky/MEHPJ5MpFBSS.webp',
            ],
            [
                'item_ID'      => 'ThumbBO5BR',
                'id_brand'     => 5,
                'id_category'  => 2,
                'model'        => "Warwick Pro Series Thumb BO 5-string Bass",
                'in_stock'     => true,
                'description'  => "5-string Electric Bass with Ovangkol Body and Neck, Wenge Fingerboard, 2 Active J-style Stacked-coil Pickups, and 2-band EQ/Preamp - Burgundy Red Transparent Satin",
                'product_info' => "Launched in 1985, the Warwick Thumb Bass found instant popularity cross-genre, thanks to a savvy design that accommodates all playing styles. Today, the Pro Series Thumb Bass BO still leads the pack of boutique-style electric basses it helped inspire. From the svelte curves of its sleek, compact, and exceedingly comfortable ovangkol body to its fast, “C”-profile bolt-on neck and precision fretwork to its tight, responsive low B string, the Thumb Bass BO 5-string feels incredible to play whether you’re plucking, picking, or slapping. Its active MEC pickups and 2-band EQ/preamp deliver a massive sound and versatile tonality that you can quickly sculpt to perfectly complement any music setting. Quality crafted by master luthiers in Germany, the Warwick Thumb Bass 5 is a high-performance thoroughbred. Take your playing to the next level with your Warwick Thumb Bass from Sweetwater!",
                'price'        => 4345.00,
                'img'          => '/img/items/bass/warwick/ThumbBO5BR.webp',
            ],
            [
                'item_ID'      => 'TRBX505BRB',
                'id_brand'     => 6,
                'id_category'  => 2,
                'model'        => "Yamaha TRBX505 5-string Bass Guitar",
                'in_stock'     => false,
                'description'  => "5-string Electric Bass with Mahogany Body, 5-piece Maple/Mahogany Neck, Rosewood Fingerboard, Active Electronics, and 2 Humbucking Pickups - Brick Burst",
                'product_info' => "The Yamaha TRBX505 5-string bass guitar brings versatility, killer looks, and amazing performance together in a complete package. This sleek-looking, great-sounding bass gives you a comfortable Yamaha body shape and a fast-action bolt-on 5-piece maple/mahogany neck with a smooth-playing rosewood fingerboard. A pair of humbucking pickups delivers hum-free sound while powerful active electronics let you optimize your bass for different playing styles. Factor in the Yamaha TRBX505’s solid hardware and thoughtful design, and you’ve got a great-looking bass that’s ready to rock any stage or studio session.",
                'price'        => 649.99,
                'img'          => '/img/items/bass/yamaha/TRBX505BRB.webp',
            ],
            // drums
            [
                'item_ID'      => 'PSK422BD',
                'id_brand'     => 7,
                'id_category'  => 3,
                'model'        => "DW Performance Series 4-piece Shell Pack with 22 inch Bass Drum",
                'in_stock'     => true,
                'description'  => '4-piece Maple Shell Pack with 10" and 12" Toms, 16" Floor Tom, and 22" Bass Drum - Black Diamond FinishPly',
                'product_info' => "The Performance Series begins with DW's US-built, handcrafted HVX hard rock North American maple shells. The HVX grain orientation arranges wood plies horizontally, vertically, and diagonally for a deep and satisfying fundamental. Shells are baked in pressure molds (2600 PSI at 200°F) then immediately Cool Tempered to crystallize the glue, maximizing strength, roundness, and resonance. Toms come crowned with pinpoint 45° back-cut bearing edges to enhance attack and increase head response; the kick drum features 60° edges for richer depth and effortless playability.",
                'price'        => 2786.00,
                'img'          => '/img/items/drums/DW/PSK422BD.webp',
            ],
            [
                'item_ID'      => 'SR628XUZXN',
                'id_brand'     => 8,
                'id_category'  => 3,
                'model'        => "Mapex Saturn VI Studioease 5-piece Shell Pack",
                'in_stock'     => false,
                'description'  => '5-piece Maple/Walnut Shell Pack with 10" and 12" Toms, 14" and 16" Floor Toms, and 22" Bass Drum - Exotic Natural Burl',
                'product_info' => "The Mapex Saturn VI Studioease shell pack blends time-honored maple/walnut shells with bleeding-edge shell technology borrowed from the Black Panther Design Lab — not to mention a jaw-dropping high-gloss lacquer finish to match any timekeeper's taste! Each piece in this set has been molded to meet the needs of stage and studio professionals. You get thin, 6-ply hybrid shells crowned with Mapex's precision SONIClear bearing edges, Remo USA heads, and Mapex Power Hoops to deliver great tone and tuneability from day one. You also get Mapex's advanced shell venting, suspension tom mounting, and floating SAS floor tom legs for excellent note length and projection. Factor in those iconic Saturn Series badges and lugs, and the Mapex Saturn VI Studioease shell pack proves itself a top contender in every category.",
                'price'        => 2399.00,
                'img'          => '/img/items/drums/mapex/SR628XUZXN.webp',
            ],
            [
                'item_ID'      => 'RS525SC-ABG',
                'id_brand'     => 9,
                'id_category'  => 3,
                'model'        => "Pearl RS525SC/C Roadshow 5-piece Drum Set",
                'in_stock'     => true,
                'description'  => '5-piece Poplar Drum Set with 10" and 12" Toms, 16" Floor Tom, 22" Bass Drum, 14" Snare, Hardware, and 2-piece Cymbal Pack - Aqua Blue Glitter',
                'product_info' => "The Pearl Roadshow makes a solid foundation for the budding drummer and a mighty club kit for the weekend warrior. It's a great-sounding set of drums on its own — its 6-ply poplar shells with modern 45-degree bearing edges deliver a modern, lively attack that's inspiring behind the kit and easy to capture with a mic. This complete 5-piece kit includes drums, cymbals, hardware — even sticks and a stick bag",
                'price'        => 725.99,
                'img'          => '/img/items/drums/pearl/RS525SC-ABG.webp',
            ],
            [
                'item_ID'      => 'AQ1StagePW',
                'id_brand'     => 10,
                'id_category'  => 3,
                'model'        => "Sonor AQ1 Stage 5-piece Shell Pack with Hardware",
                'in_stock'     => true,
                'description'  => '5-piece Birch Shell Pack with 10" and 12" Rack Toms, 16" Floor Tom, 22" Bass Drum, 14" Snare, and Complete Hardware Pack',
                'product_info' => "Expertly crafted by their stalwart engineers in Bad Berleburg, Germany, Sonor’s AQ1 Stage 5-piece Shell Pack and hardware bundle embodies value and sonic versatility. Centered on 100% birch shells, the AQ1 Stage offers a sound that is balanced and highly shapeable. An updated Smart Mount tom system reduces hardware clutter and optimizes resonance with a splendid visual elegance that will look good in any performance space or recording studio. What about stands and pedals? An included 2000 Series hardware pack supplies you with all the goods to get you playing as fast as possible. Drummers here at Sweetwater know great value when they see it, and the AQ1 Stage 5-piece Shell Pack certainly fits the bill!",
                'price'        => 1569.00,
                'img'          => '/img/items/drums/sonor/AQ1StagePW.webp',
            ],
            [
                'item_ID'      => 'CL72SDIB',
                'id_brand'     => 11,
                'id_category'  => 3,
                'model'        => "Tama Superstar Classic CL72S 7-piece Shell Pack with Snare Drum",
                'in_stock'     => true,
                'description'  => '7-piece Maple Shell Pack with 8/10/12" Toms, 14/16" Floor Toms, 22" Bass Drum, and 14" Snare Drum',
                'product_info' => "TAMA's signature thin 100% maple shells endow the Superstar Classic with bold, rich tones to awaken your grooves and power your backbeats. Low-mass, low-profile lugs reduce weight on the shells for enhanced resonance across the board. And TAMA's Star-Mount system gives you unbeatable openness from your high toms without stands. Sweetwater knows TAMA enthusiasts will appreciate this Superstar Classic's matching maple bass drum hoops and classic TAMA T-badges.",
                'price'        => 1399.00,
                'img'          => '/img/items/drums/tama/CL72SDIB.webp',
            ],
            [
                'item_ID'      => 'SBP8F3NW',
                'id_brand'     => 6,
                'id_category'  => 3,
                'model'        => "Yamaha SBP8F3 Stage Custom Bop 3-piece Shell Pack",
                'in_stock'     => false,
                'description'  => '3-piece Birch Shell Pack with 12" Tom, 14" Floor Tom, and 18" Bass Drum',
                'product_info' => "From the DNA of Yamaha's world-famous Recording Custom comes the all-birch Yamaha Stage Custom Bebop shell pack. This little kit is perfect for jazz, hip-hop, and light session work. Its thin 100% birch shells, in vibey bop sizes and complete with low-mass lugs and a lacquer finish, are free to resonate with warm, clear tones. Yet players of all stripes will revel in the birch's crisp snap and dry, cutting crack. Whether you're looking for an authentic bop kit or a travel-friendly stage companion, the Yamaha Stage Custom Birch Bebop shell pack aims to please.",
                'price'        => 699.99,
                'img'          => '/img/items/drums/yamaha/SBP8F3NW.webp',
            ],
            // accesories
            [
                'item_ID'      => 'STCsMDlxBG',
                'id_brand'     => 1,
                'id_category'  => 4,
                'model'        => "Fender Deluxe Molded Stratocaster/Telecaster Case",
                'in_stock'     => true,
                'description'  => "Deluxe Molded Hardshell Case with Plush Interior for Stratocaster or Telecaster Electric Guitars",
                'product_info' => "Transport and store your Stratocaster or Telecaster guitar in style with this Fender Deluxe Molded Strat/Tele Case, designed specifically for your instrument. Combining advanced materials with a new nested stacking design and a TSA-approved locking center latch, this case will help your guitar arrive at its destination unharmed. The large interior center pocket is the perfect place to stash accessories like picks, cable, and straps, while helping to stabilize the neck during transport. From the rock-solid military-grade outer shell to the comfortable handle and high-grade plush interior lining, this case's components have been engineered for hard-core instrument protection.",
                'price'        => 249.99,
                'img'          => '/img/items/accesories/guitar-case/STCsMDlxBG.webp',
            ],
            [
                'item_ID'      => 'GX10',
                'id_brand'     => 15,
                'id_category'  => 4,
                'model'        => "Boss GX-10 Multi Effects Processor",
                'in_stock'     => true,
                'description'  => "Guitar/Bass Multi-effects Pedal with Amp/Effects Modeling, Cabs, Mics, LCD, Expression Pedal, MIDI, Effects Loop, and USB-C Recording Interface",
                'product_info' => "Compact and eminently portable, the BOSS GX-10 multi-effects processor packs the same DSP core engine as the mighty GX-100 to deliver an ultra-authentic collection of amps and effects. There are 32 total (23 guitar and nine bass) immaculate amplifier emulations, providing you with a rich palette of tones worthy of a world-class studio locker, ranging from the iconic Roland JC-120 to vintage-era tube combos and even high-gain monsters from BOSS’s X amps series. Each amplifier features its own dedicated speaker/cab pairing, and you also get 16 custom slots to load in your favorite custom IRs. Combined with a sweeping set of classic BOSS effects, the GX-10’s nearly endless array of tones is a breeze to navigate and edit thanks to this pedal’s intuitive color LCD, customizable controls, and powerful Assign Matrix. Did we mention that the GX-10 also doubles in function as a top-class audio interface thanks to its USB-C functionality? Complete with an onboard expression pedal, an effects loop, a software editor, and expanded Bluetooth abilities with the optional BT-DUAL adapter, the BOSS GX-10 is, pound for pound, one of the most comprehensive processors you can find on the Sweetwater site, ready to serve as your stage-ready standby or the centerpiece of your studio.",
                'price'        => 431.15,
                'img'          => '/img/items/accesories/guitar-fx-pedal/GX10.webp',
            ],
            [
                'item_ID'      => 'GS525B',
                'id_brand'     => 16,
                'id_category'  => 4,
                'model'        => "Hercules Stands GS525B Multi-guitar Display Rack",
                'in_stock'     => true,
                'description'  => "Folding Guitar Rack for 5 Electric, Acoustic, or Bass Guitars",
                'product_info' => "Hercules Stands' GS525B portable guitar rack safely keeps your favorite guitars racked up and ready to roll. Ideal for the studio, stage, or home, countless Sweetwater players rely on the highly portable and versatile GS525B to support their acoustic, electric, and bass guitars. Specially formulated foam covers all contact points, with discs that separate your guitars and prevent them from touching. Yoke position is adjustable for a perfect fit, and each yoke features four pick slots for added convenience. Plus, the GS525B's folding one-piece design is easy to set up, transport, and store, making it perfect for securing your guitars at home or hitting the road.",
                'price'        => 119.99,
                'img'          => '/img/items/accesories/guitar-stand/GS525B.webp',
            ],
            [
                'item_ID'      => '74T000',
                'id_brand'     => 17,
                'id_category'  => 4,
                'model'        => "D'Addario 3-inch Padded Woven Bass Guitar Strap",
                'in_stock'     => true,
                'description'  => '3" Padded Bass Guitar Strap, Adjustable 43" to 58"',
                'product_info' => "D'Addario guitar straps let you play in comfort and style! Available in several colors, styles, and materials, D'Addario straps are made to last, giving you peace of mind when you strap on your favorite guitar or bass. These straps are available in a variety of materials, including leather, suede, and polypropylene. Whether you're looking for the ultimate in padded comfort, need eye-catching graphics for added onstage sizzle, or want a classic look to match your prized vintage axe, there's a D'Addario guitar strap that's perfect for you.",
                'price'        => 25.99,
                'img'          => '/img/items/accesories/guitar-strap/74T000.webp',
            ],
            [
                'item_ID'      => 'NT1SigBlk',
                'id_brand'     => 18,
                'id_category'  => 4,
                'model'        => "Rode NT1 Signature Series Condenser Microphone with SM6 Shockmount and Pop Filter",
                'in_stock'     => true,
                'description'  => "Large-diaphragm Condenser Cardioid Microphone with Shockmount, Pop Filter, and XLR Cable",
                'product_info' => "The NT1 Signature series microphone represents the pinnacle of Rode's iconic NT1 design, thoughtfully constructed and reasonably priced to fit the likes of any level studio environment. Its traditional large-diaphragm cardioid design is a coveted quality among a range of musicians, vocalists, and content creators. Further, an emphasis on low noise guarantees solid, versatile performance on any project. Bass-heavy vocals and high-end instrument tones are no threat to the NT1's wide 20Hz to 20kHz frequency range, ensuring crystalline occupancy over the entire audial spectrum. To top everything off, the NT1 Signature Series microphone includes an SM6 combination shockmount and pop filter, plus a 6-meter XLR cable for instant utility! If you're looking for a reliable, time-trusted microphone option at a fantastic price, look no further than the NT1 Signature series microphone from Rode.",
                'price'        => 159.00,
                'img'          => '/img/items/accesories/microphone-condenser/NT1SigBlk.webp',
            ],
            [
                'item_ID'      => 'StroboClipHD',
                'id_brand'     => 19,
                'id_category'  => 4,
                'model'        => "Peterson StroboClip HD High Definition Clip-on Strobe Tuner",
                'in_stock'     => true,
                'description'  => "Clip-on Strobe Headstock Tuner with HD Backlit LCD Display",
                'product_info' => "Wavestore instrument techs love Peterson mechanical and LCD strobe tuners because they provide legendary accuracy and reliability, session after session, year after year. The Peterson StroboClip HD LCD strobe tuner delivers that renowned precision (to a tenth of a cent) in a handy, small clip-on tuner with a detailed backlit display that's easy to read regardless of light levels. It also comes with over 50 Sweetened Tunings that are customized for specific instruments, and its soft rubber jaws are non-marring but firm enough to ensure maximum signal tracking. The StroboClip is housed in a black casing and is extremely durable for worry-free performance.",
                'price'        => 59.99,
                'img'          => '/img/items/accesories/tuner/StroboClipHD.webp',
            ],
        ];

        foreach ($products as $product) {
            WavestoreProduct::create($product);
        }
    }
}
